import Head from "next/head";
import Link from "next/link";
import { RevestureMarketplace } from "~/components/RevestureMarketplace";

export default function Marketplace() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            ReVesture <span className="text-[hsl(280,100%,70%)]">Marketplace</span>
          </h1>
          <div className="grid grid-cols-3 gap-4">
            <RevestureMarketplace address="0x8b6988D56F0176F8Aa09F7d6D04c59aad8980A1D" />
            </div>
        </div>
      </main>
    </>
  );
}
